version: "3.9"

services:

  backend:
    image: currency-backend
    build: .
    container_name: backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true

  memcached:
    image: memcached:1.6.21-alpine
    container_name: memcached
    env_file:
      - .env
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.12.4-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5673:5672"
      - "15672:15672"

  postgres:
    image: postgres:15.4-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data: {}

