# Generated by Django 4.2.3 on 2023-07-31 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_from", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.CharField(max_length=2500)),
            ],
            options={
                "verbose_name": "ContactUs",
                "verbose_name_plural": "ContactUs",
            },
        ),
        migrations.CreateModel(
            name="RequestResponseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("status_code", models.IntegerField(default=200)),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("time", models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("url", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sell",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "US Dollar"),
                            (2, "Euro"),
                            (3, "Hryvnia"),
                            (4, "Polish Zloty"),
                            (5, "Swiss Franc"),
                            (6, "Bitcoin"),
                        ],
                        default=1,
                        verbose_name="Currency",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currency.source",
                    ),
                ),
            ],
        ),
    ]
