# Generated by Django 4.2.2 on 2023-06-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
