# Generated by Django 4.2.3 on 2023-07-31 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0002_alter_rate_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="currency.source",
            ),
        ),
    ]
