# Generated by Django 4.2.2 on 2023-06-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_rate_buy_alter_rate_currency_alter_rate_sell_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contuctus',
            name='user_id',
        ),
    ]
