# Generated by Django 4.2.4 on 2023-08-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0004_source_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="logo",
            field=models.FileField(blank=True, default=None, null=True, upload_to=""),
        ),
    ]
