# Generated by Django 4.2.3 on 2023-07-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0005_alter_rates_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rates",
            name="currency",
            field=models.CharField(max_length=4),
        ),
    ]
