# Generated by Django 4.2.4 on 2023-08-04 15:14

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0006_alter_source_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="logo",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=currency.models.source_logo_path,
            ),
        ),
    ]
