# Generated by Django 4.2.3 on 2023-07-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0011_alter_rate_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestResponseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                (
                    "request_method",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "GET"), (1, "POST")],
                        default=0,
                        max_length=1,
                        verbose_name="RequestMethod",
                    ),
                ),
                ("time", models.IntegerField(max_length=20)),
            ],
        ),
    ]
