# Generated by Django 4.2.3 on 2023-07-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0012_requestresponselog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestresponselog",
            name="time",
            field=models.IntegerField(),
        ),
    ]
