# Generated by Django 4.2.3 on 2023-07-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0013_alter_requestresponselog_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestresponselog",
            name="request_method",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "GET"), (1, "POST")],
                default=0,
                verbose_name="RequestMethod",
            ),
        ),
    ]
