# Generated by Django 4.2.3 on 2023-07-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0014_alter_requestresponselog_request_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="currency",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "US Dollar"),
                    (2, "Euro"),
                    (3, "Hryvnia"),
                    (4, "Polish Zloty"),
                    (5, "Swiss Franc"),
                    (6, "Bitcoin"),
                ],
                default=1,
                verbose_name="Currency",
            ),
        ),
    ]
