# Generated by Django 4.2.3 on 2023-07-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0015_alter_rate_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestresponselog",
            name="request_method",
            field=models.CharField(default="GET", max_length=10),
        ),
    ]
