# Generated by Django 4.2.3 on 2023-07-19 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0016_alter_requestresponselog_request_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestresponselog",
            name="created",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="requestresponselog",
            name="time",
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
