# Generated by Django 4.2.3 on 2023-07-19 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0017_requestresponselog_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requestresponselog",
            old_name="request_method",
            new_name="method",
        ),
    ]
