# Generated by Django 4.2.3 on 2023-07-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0018_rename_request_method_requestresponselog_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestresponselog",
            name="status_code",
            field=models.IntegerField(default=200, max_length=3),
        ),
    ]
