# Generated by Django 4.2.3 on 2023-07-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0019_requestresponselog_status_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestresponselog",
            name="status_code",
            field=models.IntegerField(default=200),
        ),
    ]
